import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';

import { Inter } from 'next/font/google';
import MobileLayout from '@/components/MobileHeader';
import Toast from '@/components/Toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'IQ Challenge | F-Code',
    // description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                <MobileLayout>{children}</MobileLayout>
                <Toast />
            </body>
        </html>
    );
}
